### PR TITLE
Initial support for resistive screens

### PR DESCRIPTION
**Pull request by BroMarduk**
Added pitft_touchscreen support for resistive screens.

### CODE REVIEW

**Comment by nift4** [comment]
Thanks!

**Comment by BroMarduk** [comment]
Getting there.   I'll try and work on the pigame support for resistive tomorrow.    I have it working, but would like a new branch created there so we can test both the pigame and pitft_touchscreen branches and make sure they are working.

Also, I want to contact Adafruit and see if I can get a list of parameters for their dtoverlay for the screens.  It may be possible to use the boot.config setting for automatic touchscreen detection for screen, rotation and possibly GPIOs for buttons (although there are old versions that I don't think I can detect).   Otherwise additional parameter may be needed to specify the screen.  

There are some older configurations (like the one @goose2000 originally had) that may require additional parameter support.

**Comment by nift4** [comment]
Branch exists: `morehw`

**Comment by nift4** [comment]
dtoverlay dection can be hard.... But try it out!

**Pull request merged**
