### PR TITLE
Merged correctly with main fork - Sometimes I just merge things wrong. 

### PR DESCRIPTION
**Pull request by BroMarduk**

### CODE REVIEW

**Comment by BroMarduk** [comment]
Too much coffee = bad merging skills.

This should be correct.

**Comment by BroMarduk** [comment]
This version also works with Python 2.7 and allows an evdev grab, so no other apps can get messages.

No breaking changes with previous version and is compatible with current pigame, branches and existing test apps - you will notice that exiting app with a keyboard interrupt is cleaner.

Also, can you create a new branch off master here for the changes to support resistive screens?

**Comment by nift4** [comment]
Yup. Branch `resistive-support`

**Comment by nift4** [comment]
And thanks for the pull request, I'm not a evdev expert ;)

**Pull request merged**
